<div class="container">
    
    <div id="cv-div">
        <!-- On peut afficher le CV jusqu'à 775px d'écran, après il faudra mettre autre chose en place -->
        <div id="aboutme">
            <div id='info-section'>
                <img id="cv-picture" src="./assets/me.png">
                <h2 class="ctr" id="name">Sarah Leconte</h2>
                <p class="ctr" id="age">23 ans</p>
                <div id="me-info">
                    <h3 class="info-cv bold-title">CONTACT :</h3>
                    <div class="info-cv" id="mail">
                        <i class="fa-solid fa-envelope fa-lg"></i>
                        <p class="p-m-0">sarah_leconte@msn.com</p>
                    </div>
                    <div class="info-cv" id="phone">
                        <i class="fa-solid fa-phone fa-lg"></i>
                        <p class="p-m-0 phone">+33 6 05 29 72 95</p>
                    </div>
                    <div class="info-cv" id="adress">
                        <i class="fa-solid fa-house fa-lg"></i>
                        <p class="p-m-0">13 rue de l'Argonne, 45000, ORLEANS</p>
                    </div>
                    <div class="info-cv" id="car">
                        <i class="fa-solid fa-car fa-lg"></i>
                        <p class="p-m-0">Permis B + véhicule personnel</p>
                    </div>
                </div>
                <div id="hobbies-div">
                    <h3 class="info-cv bold-title">CENTRE D'INTERETS :</h3>
                    <div class="info-cv hobbies" id="lecture">
                        <img class="picture-cv" src="./assets/book.png">
                        <p class="p-m-0">Lecture</p>
                    </div>
                    <div class="info-cv hobbies" id="pets">
                        <img class="picture-cv" src="./assets/pets.png">
                        <p class="p-m-0">Animaux</p>
                    </div>
                </div>
                <div class="info-cv" id="qr-div">
                    <img id="qr-code" src="./assets/QRcode.png">
                </div>
            </div>
            <div id="cv-section">
                <div id="header">
                    <div>
                        <h2 id="cv-title">DEVELOPPEUSE WEB EN ALTERNANCE</h2>
                        <div id="alternance">
                            <p class="p-m-0">Rythme d'alternance :</p>
                            <p class="p-m-0">1<sup>ère</sup> année : 2 semaines entreprise/ 2 semaines cours</p>
                            <p class="p-m-0">2<sup>ème</sup> année : 3 semaines entreprise/ 1 semaine cours</p>
                        </div>
                        <p class="p-m-0 padd-20 size-14">Je suis une personne rigoureuse, autonome et je sais m'adapter aux différentes situations que je rencontre.</p>
                    </div>
                    <div id="round-div">
                        <div id="deco-round1"></div>
                        <div id="deco-round2"></div>
                    </div>
                </div>
                <div class="band">
                    <h3>COMPETENCES</h3>
                </div>
                <div class="div-mg" id="competence">
                    <div class="skill" id="skills">
                        <ul>
                            <li>Rédaction d'un mode opératoire</li>
                            <li>Programmation LabVIEW</li>
                            <li>Contrôle de conformité</li>
                            <li>Rédaction d'un rapport de mesure</li>
                        </ul>
                    </div>
                    <div class="skill" id="dev-skills">
                        <p class="skill-title p-m-0">FRONT-END :</p>
                        <p class="p-m-0">HTML/CSS, BOOSTRAP, UI/UX, JS</p>
                        <p class="skill-title p-m-0">BACK-END :</p>
                        <p class="p-m-0">C, PYTHON, PHP</p>
                    </div>
                </div>
                <div class="band" id="exp-pro">
                    <h3>EXPERIENCES PROFESSIONNELLES</h3>
                </div>
                <div class="div-cv-center div-mg" id="experience">
                    <p class="bold-title p-m-0">TECHNICIEN DE MESURE EN ALTERNANCE (LICENCE)/p>
                    <p class="p-m-0">Septembre 2021 à aout 2022</p>
                    <p class="p-m-4">J'ai travaillé sur l'amélioration d'un banc d'essai de mesure acoustique pour l'entreprise HUTCHINSON à JOUE-LES-TOURS</p>
                    <p class="bold-title p-m-0">TECHNICIEN QUALITE (STAGE DE BTS)</p>
                    <p class="p-m-0">Juillet 2020</p>
                    <p class="p-m-4">J'ai réalisé la création d'une gamme automatique de contrôle pour le bras de mesure tridimensionnelle FARO Edge. J'ai également réalisé des mesures de conformité pour différentes pièces pour l'entreprise SERVI DORYL à LANGEAIS.</p>
                    <p class="bold-title p-m-0">AGENT D'EXPLOITATION</p>
                    <p class="p-m-0">Mars à juillet 2019 et juin 2020</p>
                    <p class="p-m-4">J'ai réalisé de la mise sous pli des chèques vacances pour l'entreprise NUMEN SERVICES à CHAMBRAY-LES-TOURS.</p>
                </div>
                <div class="band" id="formations">
                    <h3>FORMATIONS</h3>
                </div> 
                <div class="div-cv-center div-mg" id="etudes">
                    <p class="bold-title p-m-0">BACHELOR CDA</p>
                    <p class="p-m-0 acronyme">(CONCEPTEUR, DEVELOPPEUR D'APPLICATIONS)</p>
                    <p class="p-m-4">En cours, 1ère année - CODA SCHOOL, ORLEANS</p>
                    <p class="bold-title p-m-0">NIVEAU LICENCE PRO CIME</p>
                    <p class="p-m-0 acronyme">(CAPTEURS, INSTRUMENTATION, MESURES ET ESSAIS)</p>
                    <p class="p-m-4">2022 - IUT du Limousin, LIMOGES</p>
                    <p class="bold-title p-m-0">BTS TPIL</p>
                    <p class="p-m-0 acronyme">(TECHNIQUES PHYSIQUES POUR L'INDUSTRIE ET LE LABORATOIRE)</p>
                    <p class="p-m-4">2021 - Lycée Grandmont, CHAMBRAY-LES-TOURS</p>
                </div>
                <div class="band" id="info-c">
                    <h3>INFORMATIONS COMPLEMENTAIRES</h3>
                </div>
                <div class="skill div-mg" id="info-complem">
                    <ul>
                        <li>Niveau B1 anglais (655/990 au TOEIC)</li>
                    </ul>
                </div>
                <div id="logo">
                    <img src="./assets/coda-logo" alt="" id="coda-logo">
                </div>
            </div>
            
        </div>
    </div>
    <div id="replace-cv">
        <div class='cv-min' id='aboutme-min'>
            <div id="me">
                <img id="cv-picture-min" src="./assets/me.png">
                <div>
                    <h2 class="ctr" id="name">Sarah Leconte</h2>
                    <p class="ctr" id="age">23 ans</p>
                </div>
            </div>
            <div id="info-hobbies-div">
                <div class='percent50'id="contact-div-min">
                    <h3 class="info-cv bold-title">CONTACT :</h3>
                    <div class="info-cv" id="mail">
                        <i class="fa-solid fa-envelope fa-lg"></i>
                        <p class="p-m-0">sarah_leconte@msn.com</p>
                    </div>
                    <div class="info-cv" id="phone">
                        <i class="fa-solid fa-phone fa-lg"></i>
                        <p class="p-m-0 phone">+33 6 05 29 72 95</p>
                    </div>
                    <div class="info-cv" id="adress">
                        <i class="fa-solid fa-house fa-lg"></i>
                        <p class="p-m-0">13, rue de l'Argonne <br> 45000 ORLEANS</p>
                    </div>
                    <div class="info-cv" id="car">
                        <i class="fa-solid fa-car fa-lg"></i>
                        <p class="p-m-0">Permis B + véhicule personnel</p>
                    </div>
                </div>
                <div class='percent50'id="hobbies-div">
                    <h3 class="info-cv bold-title">CENTRE D'INTERETS :</h3>
                    <div class="info-cv hobbies" id="lecture">
                        <img class="picture-cv" src="./assets/book.png">
                        <p class="p-m-0">Lecture</p>
                    </div>
                    <div class="info-cv hobbies" id="pets">
                        <img class="picture-cv" src="./assets/pets.png">
                        <p class="p-m-0">Animaux</p>
                    </div>
                </div>
            </div>
        </div>
        <div id="cv-section2">
            <div>
                <div>
                    <h2 id="cv-title2">DEVELOPPEUSE WEB EN ALTERNANCE</h2>
                    <div id="alternance2">
                        <p class="p-m-0">Rythme d'alternance :</p>
                        <p class="p-m-0">1<sup>ère</sup> année : 2 semaines entreprise/ 2 semaines cours</p>
                        <p class="p-m-0">2<sup>ème</sup> année : 3 semaines entreprise/ 1 semaine cours</p>
                    </div>
                    <p class="p-m-0 padd-10 size-14">Je suis une personne rigoureuse, autonome et je sais m'adapter aux différentes situations que je rencontre.</p>
                </div>
            </div>
            <div class="band">
                <h3>COMPETENCES</h3>
            </div>
            <div class="div-mg" id="competence2">
                <div class="skill" id="skills2">
                    <ul>
                        <li>Rédaction d'un mode opératoire</li>
                        <li>Programmation LabVIEW</li>
                        <li>Contrôle de conformité</li>
                        <li>Rédaction d'un rapport de mesure</li>
                    </ul>
                </div>
                <div class="skill" id="dev-skills2">
                    <p class="skill-title p-m-0">FRONT-END :</p>
                    <p class="p-m-0">HTML/CSS, BOOSTRAP, UI/UX, JS</p>
                    <p class="skill-title p-m-0">BACK-END :</p>
                    <p class="p-m-0">C, PYTHON, PHP</p>
                </div>
            </div>
            <div class="band" id="exp-pro2">
                <h3>EXPERIENCES PROFESSIONNELLES</h3>
            </div>
            <div class="div-cv-center div-mg" id="experience2">
                <p class="bold-title p-m-0">TECHNICIEN DE MESURE EN ALTERNANCE (LICENCE)</p>
                <p class="p-m-0">Septembre 2021 à aout 2022</p>
                <p class="p-m-4">J'ai travaillé sur l'amélioration d'un banc d'essai de mesure acoustique pour l'entreprise HUTCHINSON à JOUE-LES-TOURS</p>
                <p class="bold-title p-m-0">TECHNICIEN QUALITE (STAGE DE BTS)</p>
                <p class="p-m-0">Juillet 2020</p>
                <p class="p-m-4">J'ai réalisé la création d'une gamme automatique de contrôle pour le bras de mesure tridimensionnelle FARO Edge. J'ai également réalisé des mesures de conformité pour différentes pièces pour l'entreprise SERVI DORYL à LANGEAIS.</p>
                <p class="bold-title p-m-0">AGENT D'EXPLOITATION</p>
                <p class="p-m-0">Mars à juillet 2019 et juin 2020</p>
                <p class="p-m-4">J'ai réalisé de la mise sous pli des chèques vacances pour l'entreprise NUMEN SERVICES à CHAMBRAY-LES-TOURS.</p>
            </div>
            <div class="band" id="formations2">
                <h3>FORMATIONS</h3>
            </div> 
            <div class="div-cv-center div-mg" id="etudes2">
                <p class="bold-title p-m-0">BACHELOR CDA</p>
                <p class="p-m-0 acronyme">(CONCEPTEUR, DEVELOPPEUR D'APPLICATIONS)</p>
                <p class="p-m-4">En cours, 1ère année - CODA SCHOOL, ORLEANS</p>
                <p class="bold-title p-m-0">NIVEAU LICENCE PRO CIME</p>
                <p class="p-m-0 acronyme">(CAPTEURS, INSTRUMENTATION, MESURES ET ESSAIS)</p>
                <p class="p-m-4">2022 - IUT du Limousin, LIMOGES</p>
                <p class="bold-title p-m-0">BTS TPIL</p>
                <p class="p-m-0 acronyme">(TECHNIQUES PHYSIQUES POUR L'INDUSTRIE ET LE LABORATOIRE)</p>
                <p class="p-m-4">2021 - Lycée Grandmont, CHAMBRAY-LES-TOURS</p>
            </div>
            <div class="band" id="info-c2">
                <h3>INFORMATIONS COMPLEMENTAIRES</h3>
            </div>
            <div class="skill div-mg" id="info-complem2">
                <ul>
                    <li>Niveau B1 anglais (655/990 au TOEIC)</li>
                </ul>
            </div>
            <div id="logo2">
                <img src="./assets/coda-logo" id="coda-logo2" alt="">
            </div>
        </div>
    </div>
    <script src="./scripts/aboutme.js"></script>
</div>
