<div class="container">
    <div id="bootstrap-div">
        <h2>Projet Bootstrap</h2>
        <p>J'ai pu réaliser ce projet dans le cadre d'un cours HTML/CSS sur l'utilisation de Bootstrap. Notre professeur nous a fournit une maquette (que vous trouverez ci-dessous) et nous a demandé de la réaliser en HTML/CSS avec un maximum l'utilisation de Bootstrap.</p>
        <a href="./bootstrap" id="bootstrap-link">Cliquez ici pour voir le résultat</a>
    </div>
    <div id="boostrap-img">
        <img src="./assets/maquette.jpg" alt="Maquette Bootstrap" id="maquette">
    </div>
</div>