<div class="container homepage">
    <div class='div' id="aboutmediv">
        <h1>Recherche Alternance en développement Web</h1>
        <div id="presentation">
            <img src="./assets/me.png">
            <div class="column-center" id="mini-pres">
                <p id="pres">Etudiante en Bachelor CDA (Concepteur, développeur d'application) 1<sup>ère</sup> année chez CODA - Ecole d'informatique </p>
                <a id="meLink" href="?page=aboutme">Si vous voulez en savoir plus à propos de moi</a>
            </div>
        </div>
    </div>
    <div id="projectsdiv">
        <h2 id="project-title">MES PROJETS</h2>
        <div class="row row-cols-1 row-cols-md-2 g-4" id="mini-project">
            <div class="col">
                <a class="card cardLink" href="?page=bootstrap">
                    <img src="./assets/bootstrap.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Bootstrap Website</h5>
                        <p class="card-text">Projet réalisé à partir d'une maquette dans le cadre d'un cours sur HTML/CSS.</p>
                    </div>
                </a>
            </div>
            <div class="col">
                <a class="card cardLink" href="./pong">
                    <img src="./assets/pong.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Pong Game</h5>
                        <p class="card-text">Projet du célèbre jeu pong, réalisé dans le cadre d'un cours sur Canvas. Jouable uniquement avec un clavier.</p>
                    </div>
                </a>
            </div>
            <div class="col">
                <a class="card cardLink" href="./connect4">
                    <img src="./assets/connect4.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Connect 4</h5>
                        <p class="card-text">Projet du jeu puissance 4, réalisé dans le cadre du cours de JavaScript.</p>
                    </div>
                </a>
            </div>
            <div class="col">
                <a class="card cardLink" herf="?page=homepage">
                    <img src="./assets/portfolio.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Portfolio</h5>
                        <p class="card-text">Mon portfolio afin de pouvoir me présenter et présenter mon travail.</p>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class='div' id="contact-div">
        <h2 id="focusTitle">CONTACT</h2>
        <div class='flexRow'>
            <div class='row'>
                <div class='contactDiv'>
                    <i class="fa-solid fa-square-phone fa-2xl"></i>
                    <p class="m0 phone">+33 6 05 29 72 95</p>                
                </div>
                <div class='contactDiv'>
                    <i class="fa-solid fa-square-envelope fa-2xl"></i>
                    <p class="m0" type="email">sarah_leconte@msn.com</p>
                </div>
            </div>
            <div>
                <a class='iconLink' href="https://linktr.ee/sarahlte">
                    <i class="fa-solid fa-link fa-3x"></i>
                </a>
                <a class='iconLink' href="https://www.linkedin.com/in/sarah-leconte-21102119a">
                    <i class="fa-brands fa-linkedin fa-3x"></i>
                </a>
                <a class='iconLink' href="https://github.com/sarahlte">
                    <i class="fa-brands fa-github fa-3x"></i>
                </a>
            </div>
        </div>
        <div>

        </div>
        
    </div>
</div>